name: LightRP
version: '1.0'
main: tire.lightrp.LightRP
authors: [ TiRe ]
description: Changing the format of RP commands.
commands:
  me:
    description: Me
    usage: /me <message>
  do:
    description: Do
    usage: /do <message>
  n:
    description: NRP chat
    usage: /n <message>
